### ISSUE TITLE
ImportError: No module named BufferedImageSaver/BufferedLidarSaver AND IndexError: blueprint 'sensor.camera.normal' not found

### ISSUE THREAD

**Issue by jjimin** [Tom-Huang/carla_data_collection#1]
Hi, I have some issues with data generation.

I followed the README but when I run this 'collect_albedo_depth_normal.py', I get the errors below.

```
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "./PythonAPI/examples/collect_albedo_depth_normal.py", line 22, in <module>
    from BufferedImageSaver import BufferedImageSaver
ImportError: No module named BufferedImageSaver
```
```
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "./PythonAPI/examples/collect_albedo_depth_normal.py", line 23, in <module>
    from BufferedLidarSaver import BufferedLidarSaver
ImportError: No module named BufferedLidarSaver
```

So, I comment out a few lines with `BufferedImageSaver` and `BufferedLidarSaver`.

However, I still got another error like this.
```
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
enabling synchronous mode.

disabling synchronous mode.
done.

done.
Traceback (most recent call last):
  File "./PythonAPI/examples/collect_albedo_depth_normal.py", line 453, in <module>
    main()
  File "./PythonAPI/examples/collect_albedo_depth_normal.py", line 226, in main
    normal_to_world_blueprint = blueprints.find(SENSOR_TYPE_4_CARLA)
IndexError: blueprint 'sensor.camera.normal' not found
```
I already copied files in 'postprocess_effect_carla' to '/home/carla/CarlaUE4/Plugins/Carla/Content/PostProcessingMaterials'.

Is there anything else I need to do to run 'collect_albedo_depth_normal.py'?
(I'm using Carla 0.9.8 in docker environment.)

**Comment by Tom-Huang** [comment]
Sorry for the delay. Did you recompile carla after you did step 1 in Data Generation? Because you need to recompile carla to include the assets for normal vector used by the python code. If you don't need to use the normal vector, you can comment all the code related to SENSOR_TYPE_4_CARLA.
