### ISSUE TITLE
compiling error

### ISSUE THREAD

**Issue by Sibozhu** [Tom-Huang/carla_data_collection#2]
Dear @Tom-Huang ,

Thanks so much for sharing this amazing labeling tool! 

I'm having a small problem when I'm trying to compile your code.

Even after I did

```
Copy files in "poseprocesseffect" to "carla_root_folder/Unreal/CarlaUE4/Plugins/Carla/Content/PostProcessingMaterials"
```

I still got 
```
Traceback (most recent call last):
  File "collect_albedo_depth_normal.py", line 450, in <module>
    main()
  File "collect_albedo_depth_normal.py", line 224, in main
    normal_to_world_blueprint = blueprints.find(SENSOR_TYPE_4_CARLA)
IndexError: blueprint 'sensor.camera.normal' not found
```

Is there any step I'm missing? Or there's some way to compile those post processing materials?

Best,
Sibo

**Comment by Tom-Huang** [comment]
May I ask where did you get this error? It looks like the error from running the python code rather than compiling c++ cmake project.
Only copying those files into the folder won't work. You have to recompile the Carla as well to have those properties in the python.

**Comment by Sibozhu** [comment]
Thanks for the rapid reply!

I got this error by running `python3 collect_albedo_depth_normal.py`

Does recompile Carla meaning `make launch` or `make PythonAPI`? If so, I did both of them.

I'm trying `make rebuild` right now!

**Comment by Tom-Huang** [comment]
Yes, I suggest you delete all inside the build folder in Carla first and do the necessary steps to rebuild. If it still doesn't work, I suggest you abandon all the code relevant to sensor 4, 5, 7, 8. Because those codes are for other purposes rather than labeling lidar point cloud with semantics.
